# **Numpy tutorial**

In [ ]:
import numpy as np

In [ ]:
a = np.array([10,20,30])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([10, 20, 30])

In [ ]:
b = np.zeros(3)

In [ ]:
b

array([0., 0., 0.])

In [ ]:
c = np.ones(4)

In [ ]:
c

array([1., 1., 1., 1.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
list(range(4))

[0, 1, 2, 3]

In [ ]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(2,6,5)

array([2., 3., 4., 5., 6.])

In [ ]:
x = np.ones(4,dtype=np.int64)

In [ ]:
x

array([1, 1, 1, 1])

## Adding removing and sorting elements

In [ ]:
a = np.array([2,1,9,6,8,0])

In [ ]:
a

array([2, 1, 9, 6, 8, 0])

In [ ]:
a.sort()

In [ ]:
a

array([0, 1, 2, 6, 8, 9])

In [ ]:
x = np.array([10,20,30,40])
y = np.array([50,60,70,80])

In [ ]:
x

array([10, 20, 30, 40])

In [ ]:
y

array([50, 60, 70, 80])

In [ ]:
np.concatenate((x,y))

array([10, 20, 30, 40, 50, 60, 70, 80])

## Reshaping array

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.shape

(10,)

In [ ]:
b = a.reshape(2,5)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b.shape

(2, 5)

In [ ]:
b.size

10

In [ ]:
b.ndim

2

In [ ]:
x = np.array([2,3,4,5,6,7,8,100])

In [ ]:
x.size

8

In [ ]:
x.reshape(2,4)

array([[  2,   3,   4,   5],
       [  6,   7,   8, 100]])

In [ ]:
x.reshape(4,2)

array([[  2,   3],
       [  4,   5],
       [  6,   7],
       [  8, 100]])

In [ ]:
x.reshape(8,1)

array([[  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [100]])

In [ ]:
x.reshape(1,8)

array([[  2,   3,   4,   5,   6,   7,   8, 100]])

## Slicing and Indexing arrays

In [ ]:
x = np.arange(10)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[0]

0

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[2:5]

array([2, 3, 4])

In [ ]:
x[-2:]

array([8, 9])

In [ ]:
x = np.arange(10)

In [ ]:
y = x.reshape(2,5)

In [ ]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
y[0]

array([0, 1, 2, 3, 4])

In [ ]:
y[1]

array([5, 6, 7, 8, 9])

In [ ]:
y[:,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
y[0,-1]

4

In [ ]:
y[1,3:]

array([8, 9])

In [ ]:
y[:,1]

array([1, 6])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[x<4]  

array([0, 1, 2, 3])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[x%2==0]

array([0, 2, 4, 6, 8])

In [ ]:
bool = x%2==0

In [ ]:
x[bool]

array([0, 2, 4, 6, 8])

In [ ]:
odd = x%2!=0

In [ ]:
x[odd]

array([1, 3, 5, 7, 9])

In [ ]:
a = (10,20,30)
b = (100,400,900)

In [ ]:
z = zip(a,b)

In [ ]:
list(z)

[(10, 100), (20, 400), (30, 900)]

In [ ]:
d = dict(zip(a,b))

In [ ]:
d

{10: 100, 20: 400, 30: 900}

In [ ]:
d[10]

100

In [ ]:
d[20]

400

In [ ]:
a1 = np.array([
               [10,20,30],
               [40,50,60]
])

In [ ]:
a1.shape

(2, 3)

In [ ]:
a1

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
a2 = np.array([
               [-1,-2,-3],
               [-4,-5,-6]
])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a1

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
a2

array([[-1, -2, -3],
       [-4, -5, -6]])

In [ ]:
v = np.vstack((a1,a2))

In [ ]:
v.shape

(4, 3)

In [ ]:
v

array([[10, 20, 30],
       [40, 50, 60],
       [-1, -2, -3],
       [-4, -5, -6]])

In [ ]:
h = np.hstack((a1,a2))

In [ ]:
h

array([[10, 20, 30, -1, -2, -3],
       [40, 50, 60, -4, -5, -6]])

## BASIC ARRAY OPERATIONS

In [ ]:
a = np.array([10,20,30])
b = np.array([1,2,3])

a+b

array([11, 22, 33])

In [ ]:
a-b

array([ 9, 18, 27])

In [ ]:
a*b

array([10, 40, 90])

In [ ]:
a/b

array([10., 10., 10.])

In [ ]:
a.sum()


60

In [ ]:
b.sum()

6

In [ ]:
x = np.array([[1,2,3],[4,5,6]])


In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.sum(axis=0) # axis=0 returns sum of row elemenst

array([5, 7, 9])

In [ ]:
x.sum(axis=1) # axis=1 returns sum of column elemenst

array([ 6, 15])

## BROADCASTING

In [ ]:
x = np.array([10,20,30])
x*0.5

array([ 5., 10., 15.])

## More useful Array operations

In [ ]:
x = np.arange(10)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.min()

0

In [ ]:
x.max()

9

In [ ]:
x.mean()

4.5

In [ ]:
x.std()

2.8722813232690143

In [ ]:
x.prod()

0

In [ ]:
y = np.arange(1,10,2)

In [ ]:
y

array([1, 3, 5, 7, 9])

In [ ]:
y.prod()

945

In [ ]:
data = np.arange(10).reshape(5,2)

In [ ]:
data

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
data.min(axis=0)

array([0, 1])

In [ ]:
data.min(axis=1)

array([0, 2, 4, 6, 8])

In [ ]:
data.prod(axis=1)

array([ 0,  6, 20, 42, 72])

In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([1,2])

In [ ]:
x+y

array([[2, 4],
       [4, 6],
       [6, 8]])

In [ ]:
x.shape

(3, 2)

In [ ]:
y.shape

(2,)

In [ ]:
x = np.arange(12)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
x.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
import random

In [ ]:
random.randint(1,10)

1

In [ ]:
random.random()

0.4493125453679384

In [ ]:
help(random.random)

Help on built-in function random:

random(...) method of random.Random instance
    random() -> x in the interval [0, 1).



In [ ]:
help(random.randrange)

Help on method randrange in module random:

randrange(start, stop=None, step=1, _int=<class 'int'>) method of random.Random instance
    Choose a random item from range(start, stop[, step]).
    
    This fixes the problem with randint() which includes the
    endpoint; in Python this is usually not what you want.



In [ ]:
random.randrange(1,100)

2

In [ ]:
random.randrange(1,10,2)

5

## how to get unique items and count

In [ ]:
x = np.array([1,1,2,1,3,3,4,5,1,2,1])

In [ ]:
x

array([1, 1, 2, 1, 3, 3, 4, 5, 1, 2, 1])

In [ ]:
np.unique(x)

array([1, 2, 3, 4, 5])

In [ ]:
val,ind = np.unique(x,return_index=True)

In [ ]:
val

array([1, 2, 3, 4, 5])

In [ ]:
ind

array([0, 2, 4, 6, 7])

In [ ]:
val,count = np.unique(x,return_counts=True)

In [ ]:
val

array([1, 2, 3, 4, 5])

In [ ]:
count

array([5, 2, 2, 1, 1])

## Transpose

In [ ]:
x = np.arange(6).reshape(2,3)

In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

## Reversing an array

In [ ]:
x = np.array([1,2,3])

In [ ]:
np.flip(x)

array([3, 2, 1])

In [ ]:
y = np.arange(6).reshape(2,3)

In [ ]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.flip(y)

array([[5, 4, 3],
       [2, 1, 0]])

## Flatten and Ravel

In [ ]:
y

NameError: ignored

In [ ]:
f = y.flatten()

In [ ]:
f

In [ ]:
f[0]=100

In [ ]:
f

In [ ]:
y

In [ ]:
r = y.ravel()

In [ ]:
r

In [ ]:
r[0]=100

In [ ]:
r

In [ ]:
y

In [ ]:
y?

In [ ]:
def sum():
  '''return sum of two integers'''
  return (10+2)

In [ ]:
sum?

In [ ]:
sum??

In [ ]:
random.random?

## Mathematical equivalent

In [ ]:
y = np.array([1,1,0,1])
y_pred = np.array([1,0,0,1])

In [ ]:
err = (1/4)*(np.sum(np.square(y-y_pred)))

In [ ]:
err

0.25